# Generated by Django 4.1.1 on 2022-10-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='choice',
            field=models.CharField(blank=True, choices=[('one', 'Selling'), ('two', 'Renting')], max_length=10, null=True),
        ),
    ]
