# Generated by Django 4.1.1 on 2022-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('Selling', 'Selling'), ('Renting', 'Renting')], max_length=10, null=True),
        ),
    ]
