# Generated by Django 4.1.1 on 2022-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='favorite',
        ),
        migrations.AddField(
            model_name='listing',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
