# Generated by Django 4.1.1 on 2022-10-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='images/'),
            preserve_default='True',
        ),
    ]
