# Generated by Django 4.1.1 on 2022-10-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='choice',
        ),
    ]
