# Generated by Django 4.1.2 on 2022-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='choice',
            field=models.CharField(blank=True, choices=[('Selling', 'Selling'), ('Renting', 'Renting')], max_length=10, null=True),
        ),
    ]
