# Generated by Django 4.1.1 on 2022-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_housing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], max_length=10, null=True),
        ),
    ]
